// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtQskvXc3544ztGCdZZdnAUiZO4DGa_8',
    appId: '1:634914964316:web:72f787bddf7cb70cad3799',
    messagingSenderId: '634914964316',
    projectId: 'mon-marche-domestique',
    authDomain: 'mon-marche-domestique.firebaseapp.com',
    storageBucket: 'mon-marche-domestique.firebasestorage.app',
    measurementId: 'G-9STNYVJJZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv5OF05GHpn0H23JgQmO3qHUQDcuARFYY',
    appId: '1:634914964316:android:2e22bce618015cc0ad3799',
    messagingSenderId: '634914964316',
    projectId: 'mon-marche-domestique',
    storageBucket: 'mon-marche-domestique.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXnwT8pSFpmKC7CDfy3NOY5Qi_BhkiuuI',
    appId: '1:634914964316:ios:a8943a9c5ad47880ad3799',
    messagingSenderId: '634914964316',
    projectId: 'mon-marche-domestique',
    storageBucket: 'mon-marche-domestique.firebasestorage.app',
    iosBundleId: 'com.example.monMarcheDomestique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXnwT8pSFpmKC7CDfy3NOY5Qi_BhkiuuI',
    appId: '1:634914964316:ios:a8943a9c5ad47880ad3799',
    messagingSenderId: '634914964316',
    projectId: 'mon-marche-domestique',
    storageBucket: 'mon-marche-domestique.firebasestorage.app',
    iosBundleId: 'com.example.monMarcheDomestique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCtQskvXc3544ztGCdZZdnAUiZO4DGa_8',
    appId: '1:634914964316:web:beb37a884c8b5609ad3799',
    messagingSenderId: '634914964316',
    projectId: 'mon-marche-domestique',
    authDomain: 'mon-marche-domestique.firebaseapp.com',
    storageBucket: 'mon-marche-domestique.firebasestorage.app',
    measurementId: 'G-V26NE6EHGX',
  );

}